unit General.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[categories]', '[general]')]
  TCategoryEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FReserved: Boolean;
    FParentId: Nullable<TGuid>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Reserved', [cpRequired])]
    property Reserved: Boolean read FReserved write FReserved;
    [Column('ParentId')]
    property ParentId: Nullable<TGuid> read FParentId write FParentId;
  end;

implementation

end.
