unit Address.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[states]', '[address]')]
  TStateEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FAcronym: Nullable<string>;
    FCountryId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Acronym')]
    property Acronym: Nullable<string> read FAcronym write FAcronym;
    [Column('CountryId', [cpRequired])]
    property CountryId: TGuid read FCountryId write FCountryId;
  end;

  [Entity]
  [Table('[state_codes]', '[address]')]
  TStateCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FCodeType: string;
    FCode: string;
    FStateId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('CodeType', [cpRequired])]
    property CodeType: string read FCodeType write FCodeType;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('StateId', [cpRequired])]
    property StateId: TGuid read FStateId write FStateId;
  end;

  [Entity]
  [Table('[cities]', '[address]')]
  TCityEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FAreaCodeId: TGuid;
    FStateId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('AreaCodeId')]
    property AreaCodeId: TGuid read FAreaCodeId write FAreaCodeId;
    [Column('StateId', [cpRequired])]
    property StateId: TGuid read FStateId write FStateId;
  end;

  [Entity]
  [Table('[city_codes]', '[address]')]
  TCityCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FCodeType: string;
    FCode: string;
    FCityId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('CodeType', [cpRequired])]
    property CodeType: string read FCodeType write FCodeType;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('CityId', [cpRequired])]
    property CityId: TGuid read FCityId write FCityId;
  end;

  [Entity]
  [Table('[neighborhoods]', '[address]')]
  TNeighborhoodEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FCityId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('CityId', [cpRequired])]
    property CityId: TGuid read FCityId write FCityId;
  end;

  [Entity]
  [Table('[streets]', '[address]')]
  TStreetEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
  end;

  [Entity]
  [Table('[streettypes]', '[address]')]
  TStreetTypeEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
  end;

  [Entity]
  [Table('[addresses]', '[address]')]
  TAddressEntity = class(TEntity)
  private
    FId: TGuid;
    FAddress: string;
    FNumber: string;
    FZipCode: string;
    FStreetTypeId: TGuid;
    FStreetId: TGuid;
    FNeighborhoodId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Address', [cpDontInsert, cpDontUpdate])]
    property Address: string read FAddress write FAddress;
    [Column('Number')]
    property Number: string read FNumber write FNumber;
    [Column('ZipCode', [cpRequired])]
    property ZipCode: string read FZipCode write FZipCode;
    [Column('StreetTypeId', [cpRequired])]
    property StreetTypeId: TGuid read FStreetTypeId write FStreetTypeId;
    [Column('StreetId', [cpRequired])]
    property StreetId: TGuid read FStreetId write FStreetId;
    [Column('NeighborhoodId', [cpRequired])]
    property NeighborhoodId: TGuid read FNeighborhoodId write FNeighborhoodId;
  end;

implementation

end.

