unit Inventory.Inf.Entities;

interface

uses
{PROJECT}
  Catalog.Inf.Entities,
  CRM.Inf.Entities,
  Domain.Inf.Entities,
  General.Inf.Entities,
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[warehouses]', '[inventory]')]
  TWarehouseEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FActive: Boolean;
    FDomainId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
  public
    property Domain: TDomainEntity read FDomain;
  end;

  [Entity]
  [Table('[inventories]', '[inventory]')]
  TInventoryEntity = class(TEntity)
  private
    FId: TGuid;
    FCurrentStock: Currency;
    FMinimumStock: Currency;
    FReservedStock: Currency;
    FVariantId: TGuid;
    FWarehouseId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FWarehouse: TWarehouseEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('CurrentStock', [cpRequired])]
    property CurrentStock: Currency read FCurrentStock write FCurrentStock;
    [Column('MinimumStock', [cpRequired])]
    property MinimumStock: Currency read FMinimumStock write FMinimumStock;
    [Column('ReservedStock', [cpRequired])]
    property ReservedStock: Currency read FReservedStock write FReservedStock;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('WarehouseId', [cpRequired])]
    [ForeignJoinColumn('WarehouseId', '[inventory].[warehouses]', 'Id')]
    property WarehouseId: TGuid read FWarehouseId write FWarehouseId;
  public
    property Variant: TVariantEntity read FVariant;
    property Warehouse: TWarehouseEntity read FWarehouse;
  end;

  [Entity]
  [Table('[lots]', '[inventory]')]
  TLotEntity = class(TEntity)
  private
    FId: TGuid;
    FVariantId: TGuid;
    FLotNumber: string;
    FManufacturingDate: Nullable<TDateTime>;
    FExpirationDate: Nullable<TDateTime>;
    FCostPrice: Currency;
    FSupplierId: Nullable<TGuid>;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FSupplier: TSupplierEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('LotNumber', [cpRequired])]
    property LotNumber: string read FLotNumber write FLotNumber;
    [Column('ManufacturingDate')]
    property ManufacturingDate: Nullable<TDateTime> read FManufacturingDate write FManufacturingDate;
    [Column('ExpirationDate')]
    property ExpirationDate: Nullable<TDateTime> read FExpirationDate write FExpirationDate;
    [Column('CostPrice', [cpRequired])]
    property CostPrice: Currency read FCostPrice write FCostPrice;
    [Column('SupplierId')]
    [ForeignJoinColumn('SupplierId', '[crm].[suppliers]', 'Id')]
    property SupplierId: Nullable<TGuid> read FSupplierId write FSupplierId;
  public
    property Supplier: TSupplierEntity read FSupplier;
    property Variant: TVariantEntity read FVariant;
  end;

  [Entity]
  [Table('[lot_stocks]', '[inventory]')]
  TLotStockEntity = class(TEntity)
  private
    FId: TGuid;
    FWarehouseId: TGuid;
    FLotId: TGuid;
    FCurrentStock: Currency;
    FReservedStock: Currency;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FLot: TLotEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FWarehouse: TWarehouseEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('WarehouseId', [cpRequired])]
    [ForeignJoinColumn('WarehouseId', '[inventory].[warehouses]', 'Id')]
    property WarehouseId: TGuid read FWarehouseId write FWarehouseId;
    [Column('LotId', [cpRequired])]
    [ForeignJoinColumn('LotId', '[inventory].[lots]', 'Id')]
    property LotId: TGuid read FLotId write FLotId;
    [Column('CurrentStock', [cpRequired])]
    property CurrentStock: Currency read FCurrentStock write FCurrentStock;
    [Column('ReservedStock', [cpRequired])]
    property ReservedStock: Currency read FReservedStock write FReservedStock;
  public
    property Lot: TLotEntity read FLot;
    property Warehouse: TWarehouseEntity read FWarehouse;
  end;

  [Entity]
  [Table('[transactions]', '[inventory]')]
  TTransactionEntity = class(TEntity)
  private
    FId: TGuid;
    FSequence: Int64;
    FWarehouseId: TGuid;
    FLotId: Nullable<TGuid>;
    FVariantId: TGuid;
    FTransactionTypeId: TGuid;
    FTransactionDate: TDateTime;
    FQuantity: Currency;
    FConvertedQuantity: Currency;
    FUnitMeasureId: TGuid;
    FBalanceBefore: Currency;
    FBalanceAfter: Currency;
    FReferenceTypeId: TGuid;
    FReferenceId: TGuid;
    FNotes: Nullable<string>;
    FCreatedAt: TDateTime;
    FCreatedBy: string;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FLot: TLotEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FReferenceType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FTransactionType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FWarehouse: TWarehouseEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Sequence', [cpRequired])]
    property Sequence: Int64 read FSequence write FSequence;
    [Column('WarehouseId', [cpRequired])]
    [ForeignJoinColumn('WarehouseId', '[inventory].[warehouses]', 'Id')]
    property WarehouseId: TGuid read FWarehouseId write FWarehouseId;
    [Column('LotId')]
    [ForeignJoinColumn('LotId', '[inventory].[lots]', 'Id')]
    property LotId: Nullable<TGuid> read FLotId write FLotId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('TransactionTypeId', [cpRequired])]
    [ForeignJoinColumn('TransactionTypeId', '[general].[categories]', 'Id')]
    property TransactionTypeId: TGuid read FTransactionTypeId write FTransactionTypeId;
    [Column('TransactionDate', [cpRequired])]
    property TransactionDate: TDateTime read FTransactionDate write FTransactionDate;
    [Column('Quantity', [cpRequired])]
    property Quantity: Currency read FQuantity write FQuantity;
    [Column('ConvertedQuantity', [cpRequired])]
    property ConvertedQuantity: Currency read FConvertedQuantity write FConvertedQuantity;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
    [Column('BalanceBefore', [cpRequired])]
    property BalanceBefore: Currency read FBalanceBefore write FBalanceBefore;
    [Column('BalanceAfter', [cpRequired])]
    property BalanceAfter: Currency read FBalanceAfter write FBalanceAfter;
    [Column('ReferenceTypeId', [cpRequired])]
    [ForeignJoinColumn('ReferenceTypeId', '[general].[categories]', 'Id')]
    property ReferenceTypeId: TGuid read FReferenceTypeId write FReferenceTypeId;
    [Column('ReferenceId', [cpRequired])]
    property ReferenceId: TGuid read FReferenceId write FReferenceId;
    [Column('Notes')]
    property Notes: Nullable<string> read FNotes write FNotes;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt: TDateTime read FCreatedAt write FCreatedAt;
    [Column('CreatedBy', [cpRequired])]
    property CreatedBy: string read FCreatedBy write FCreatedBy;
  public
    property Lot: TLotEntity read FLot;
    property ReferenceType: TCategoryEntity read FReferenceType write FReferenceType;
    property TransactionType: TCategoryEntity read FTransactionType write FTransactionType;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
    property Variant: TVariantEntity read FVariant;
    property Warehouse: TWarehouseEntity read FWarehouse;
  end;

  [Entity]
  [Table('[reservations]', '[inventory]')]
  TReservationEntity = class(TEntity)
  private
    FId: TGuid;
    FWarehouseId: TGuid;
    FLotId: Nullable<TGuid>;
    FVariantId: TGuid;
    FQuantity: Currency;
    FReservationDate: TDateTime;
    FExpirationDate: Nullable<TDateTime>;
    FReferenceTypeId: TGuid;
    FReferenceId: TGuid;
    FStatusId: TGuid;
    FNotes: Nullable<string>;
    FCreatedAt: TDateTime;
    FCreatedBy: string;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FLot: TLotEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FReferenceType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FStatus: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FWarehouse: TWarehouseEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('WarehouseId', [cpRequired])]
    [ForeignJoinColumn('WarehouseId', '[inventory].[warehouses]', 'Id')]
    property WarehouseId: TGuid read FWarehouseId write FWarehouseId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('LotId')]
    [ForeignJoinColumn('LotId', '[inventory].[lots]', 'Id')]
    property LotId: Nullable<TGuid> read FLotId write FLotId;
    [Column('Quantity', [cpRequired])]
    property Quantity: Currency read FQuantity write FQuantity;
    [Column('ReservationDate', [cpRequired])]
    property ReservationDate: TDateTime read FReservationDate write FReservationDate;
    [Column('ExpirationDate')]
    property ExpirationDate: Nullable<TDateTime> read FExpirationDate write FExpirationDate;
    [Column('ReferenceTypeId', [cpRequired])]
    [ForeignJoinColumn('ReferenceTypeId', '[general].[categories]', 'Id')]
    property ReferenceTypeId: TGuid read FReferenceTypeId write FReferenceTypeId;
    [Column('ReferenceId', [cpRequired])]
    property ReferenceId: TGuid read FReferenceId write FReferenceId;
    [Column('StatusId', [cpRequired])]
    [ForeignJoinColumn('StatusId', '[general].[categories]', 'Id')]
    property StatusId: TGuid read FStatusId write FStatusId;
    [Column('Notes')]
    property Notes: Nullable<string> read FNotes write FNotes;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt: TDateTime read FCreatedAt write FCreatedAt;
    [Column('CreatedBy', [cpRequired])]
    property CreatedBy: string read FCreatedBy write FCreatedBy;
  public
    property Lot: TLotEntity read FLot;
    property ReferenceType: TCategoryEntity read FReferenceType write FReferenceType;
    property Status: TCategoryEntity read FStatus write FStatus;
    property Variant: TVariantEntity read FVariant;
    property Warehouse: TWarehouseEntity read FWarehouse;
  end;

implementation

end.
