unit Inventory.Inf.Entities;

interface

uses
{PROJECT}
  Catalog.Inf.Entities,
  Domain.Inf.Entities,
  General.Inf.Entities,
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[inventories]', '[inventory]')]
  TInventoryEntity = class(TEntity)
  private
    FId: TGuid;
    FCurrentStock: Currency;
    FMinimumStock: Currency;
    FReservedStock: Currency;
    FDomainId: TGuid;
    FVariantId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('CurrentStock', [cpRequired])]
    property CurrentStock: Currency read FCurrentStock write FCurrentStock;
    [Column('MinimumStock', [cpRequired])]
    property MinimumStock: Currency read FMinimumStock write FMinimumStock;
    [Column('ReservedStock', [cpRequired])]
    property ReservedStock: Currency read FReservedStock write FReservedStock;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
  public
    property Domain: TDomainEntity read FDomain;
    property Variant: TVariantEntity read FVariant;
  end;

  [Entity]
  [Table('[transactions]', '[inventory]')]
  TTransactionEntity = class(TEntity)
  private
    FId: TGuid;
    FDomainId: TGuid;
    FVariantId: TGuid;
    FTransactionTypeId: TGuid;
    FTransactionDate: TDateTime;
    FQuantity: Currency;
    FConvertedQuantity: Currency;
    FUnitMeasureId: TGuid;
    FBalanceBefore: Currency;
    FBalanceAfter: Currency;
    FReferenceTypeId: TGuid;
    FReferenceId: TGuid;
    FNotes: Nullable<string>;
    FCreatedAt: TDateTime;
    FCreatedBy: string;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FReferenceType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FTransactionType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('TransactionTypeId', [cpRequired])]
    [ForeignJoinColumn('TransactionTypeId', '[general].[categories]', 'Id')]
    property TransactionTypeId: TGuid read FTransactionTypeId write FTransactionTypeId;
    [Column('TransactionDate', [cpRequired])]
    property TransactionDate: TDateTime read FTransactionDate write FTransactionDate;
    [Column('Quantity', [cpRequired])]
    property Quantity: Currency read FQuantity write FQuantity;
    [Column('ConvertedQuantity', [cpRequired])]
    property ConvertedQuantity: Currency read FConvertedQuantity write FConvertedQuantity;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
    [Column('BalanceBefore', [cpRequired])]
    property BalanceBefore: Currency read FBalanceBefore write FBalanceBefore;
    [Column('BalanceAfter', [cpRequired])]
    property BalanceAfter: Currency read FBalanceAfter write FBalanceAfter;
    [Column('ReferenceTypeId', [cpRequired])]
    [ForeignJoinColumn('ReferenceTypeId', '[general].[categories]', 'Id')]
    property ReferenceTypeId: TGuid read FReferenceTypeId write FReferenceTypeId;
    [Column('ReferenceId', [cpRequired])]
    property ReferenceId: TGuid read FReferenceId write FReferenceId;
    [Column('Notes')]
    property Notes: Nullable<string> read FNotes write FNotes;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt: TDateTime read FCreatedAt write FCreatedAt;
    [Column('CreatedBy', [cpRequired])]
    property CreatedBy: string read FCreatedBy write FCreatedBy;
  public
    property Domain: TDomainEntity read FDomain;
    property ReferenceType: TCategoryEntity read FReferenceType write FReferenceType;
    property TransactionType: TCategoryEntity read FTransactionType write FTransactionType;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
    property Variant: TVariantEntity read FVariant;
  end;

  [Entity]
  [Table('[reservations]', '[inventory]')]
  TReservationEntity = class(TEntity)
  private
    FId: TGuid;
    FDomainId: TGuid;
    FVariantId: TGuid;
    FQuantity: Currency;
    FReservationDate: TDateTime;
    FExpirationDate: Nullable<TDateTime>;
    FReferenceTypeId: TGuid;
    FReferenceId: TGuid;
    FStatusId: TGuid;
    FNotes: Nullable<string>;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FReferenceType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FStatus: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('Quantity', [cpRequired])]
    property Quantity: Currency read FQuantity write FQuantity;
    [Column('ReservationDate', [cpRequired])]
    property ReservationDate: TDateTime read FReservationDate write FReservationDate;
    [Column('ExpirationDate')]
    property ExpirationDate: Nullable<TDateTime> read FExpirationDate write FExpirationDate;
    [Column('ReferenceTypeId', [cpRequired])]
    [ForeignJoinColumn('ReferenceTypeId', '[general].[categories]', 'Id')]
    property ReferenceTypeId: TGuid read FReferenceTypeId write FReferenceTypeId;
    [Column('ReferenceId', [cpRequired])]
    property ReferenceId: TGuid read FReferenceId write FReferenceId;
    [Column('StatusId', [cpRequired])]
    [ForeignJoinColumn('StatusId', '[general].[categories]', 'Id')]
    property StatusId: TGuid read FStatusId write FStatusId;
    [Column('Notes')]
    property Notes: Nullable<string> read FNotes write FNotes;
  public
    property Domain: TDomainEntity read FDomain;
    property ReferenceType: TCategoryEntity read FReferenceType write FReferenceType;
    property Status: TCategoryEntity read FStatus write FStatus;
    property Variant: TVariantEntity read FVariant;
  end;

implementation

end.
