unit Person.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[persons]', '[person]')]
  TPersonEntity = class(TEntity)
  private
    FId: TGuid;
    FPersonTypeId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('PersonTypeId', [cpRequired])]
    property PersonTypeId: TGuid read FPersonTypeId write FPersonTypeId;
  end;

  [Entity]
  [Table('[legals]', '[person]')]
  TLegalEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FDoingBusinessAs: string;
    FCRN: string;
    FFoundationDate: TDateTime;
    FStateInscriptionNumber: Nullable<string>;
    FMunicipalInscriptionNumber: Nullable<string>;
    FCompanyTypeId: TGuid;
    FNationalityId: TGuid;
    FStateId: Nullable<TGuid>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('DoingBusinessAs', [cpRequired])]
    property DoingBusinessAs: string read FDoingBusinessAs write FDoingBusinessAs;
    [Column('CRN', [cpRequired])]
    property CRN: string read FCRN write FCRN;
    [Column('FoundationDate', [cpRequired])]
    property FoundationDate: TDateTime read FFoundationDate write FFoundationDate;
    [Column('StateInscriptionNumber')]
    property StateInscriptionNumber: Nullable<string> read FStateInscriptionNumber write FStateInscriptionNumber;
    [Column('MunicipalInscriptionNumber')]
    property MunicipalInscriptionNumber: Nullable<string> read FMunicipalInscriptionNumber write FMunicipalInscriptionNumber;
    [Column('CompanyTypeId', [cpRequired])]
    property CompanyTypeId: TGuid read FCompanyTypeId write FCompanyTypeId;
    [Column('NationalityId', [cpRequired])]
    property NationalityId: TGuid read FNationalityId write FNationalityId;
    [Column('StateId')]
    property StateId: Nullable<TGuid> read FStateId write FStateId;
  end;

  [Entity]
  [Table('[naturals]', '[person]')]
  TNaturalEntity = class(TEntity)
  private
    FId: TGuid;
    FFirstName: string;
    FLastName: Nullable<string>;
    FFullName: string;
    FBirthday: Nullable<TDateTime>;
    FSSN: string;
    FPlaceOfBirthId: Nullable<TGuid>;
    FNationalityId: Nullable<TGuid>;
    FGenderId: Nullable<TGuid>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('FirstName', [cpRequired])]
    property FirstName: string read FFirstName write FFirstName;
    [Column('LastName')]
    property LastName: Nullable<string> read FLastName write FLastName;
    [Column('FullName', [cpDontInsert, cpDontUpdate])]
    property FullName: string read FFullName write FFullName;
    [Column('Birthday')]
    property Birthday: Nullable<TDateTime> read FBirthday write FBirthday;
    [Column('SSN', [cpRequired])]
    property SSN: string read FSSN write FSSN;
    [Column('PlaceOfBirthId')]
    property PlaceOfBirthId: Nullable<TGuid> read FPlaceOfBirthId write FPlaceOfBirthId;
    [Column('NationalityId')]
    property NationalityId: Nullable<TGuid> read FNationalityId write FNationalityId;
    [Column('GenderId')]
    property GenderId: Nullable<TGuid> read FGenderId write FGenderId;
  end;

  [Entity]
  [Table('[addresses]', '[person]')]
  TPersonAddressEntity = class(TEntity)
  private
    FId: TGuid;
    FPersonId: TGuid;
    FTypeId: TGuid;
    FAdditionalInformation: Nullable<string>;
    FCorrespondence: Boolean;
    FAddressId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('PersonId', [cpRequired])]
    property PersonId: TGuid read FPersonId write FPersonId;
    [Column('TypeId', [cpRequired])]
    property TypeId: TGuid read FTypeId write FTypeId;
    [Column('AdditionalInformation')]
    property AdditionalInformation: Nullable<string> read FAdditionalInformation write FAdditionalInformation;
    [Column('Correspondence', [cpRequired])]
    property Correspondence: Boolean read FCorrespondence write FCorrespondence;
    [Column('AddressId', [cpRequired])]
    property AddressId: TGuid read FAddressId write FAddressId;
  end;

  [Entity]
  [Table('[emails]', '[person]')]
  TPersonEmailEntity = class(TEntity)
  private
    FId: TGuid;
    FPersonId: TGuid;
    FTypeId: TGuid;
    FAddress: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('PersonId', [cpRequired])]
    property PersonId: TGuid read FPersonId write FPersonId;
    [Column('TypeId', [cpRequired])]
    property TypeId: TGuid read FTypeId write FTypeId;
    [Column('Address', [cpRequired])]
    property Address: string read FAddress write FAddress;
  end;

  [Entity]
  [Table('[phones]', '[person]')]
  TPersonPhoneEntity = class(TEntity)
  private
    FId: TGuid;
    FPersonId: TGuid;
    FTypeId: TGuid;
    FNumber: string;
    FCityId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('PersonId', [cpRequired])]
    property PersonId: TGuid read FPersonId write FPersonId;
    [Column('TypeId', [cpRequired])]
    property TypeId: TGuid read FTypeId write FTypeId;
    [Column('Number', [cpRequired])]
    property Number: string read FNumber write FNumber;
    [Column('CityId', [cpRequired])]
    property CityId: TGuid read FCityId write FCityId;
  end;

implementation

end.
