unit CRM.Inf.Entities;

interface

uses
{PROJECT}
  Domain.Inf.Entities,
  Person.Inf.Entities,
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[customers]', '[crm]')]
  TCustomerEntity = class(TEntity)
  private
    FId: TGuid;
    FActive: Boolean;
    FDomainId: TGuid;
    FPersonId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FPerson: TPersonEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('PersonId', [cpRequired])]
    [ForeignJoinColumn('PersonId', '[person].[persons]', 'Id')]
    property PersonId: TGuid read FPersonId write FPersonId;
  public
    property Domain: TDomainEntity read FDomain;
    property Person: TPersonEntity read FPerson;
  end;

  [Entity]
  [Table('[manufacturers]', '[crm]')]
  TManufacturerEntity = class(TEntity)
  private
    FId: TGuid;
    FActive: Boolean;
    FDomainId: TGuid;
    FPersonId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FPerson: TPersonEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('PersonId', [cpRequired])]
    [ForeignJoinColumn('PersonId', '[person].[persons]', 'Id')]
    property PersonId: TGuid read FPersonId write FPersonId;
  public
    property Domain: TDomainEntity read FDomain;
    property Person: TPersonEntity read FPerson;
  end;

  [Entity]
  [Table('[suppliers]', '[crm]')]
  TSupplierEntity = class(TEntity)
  private
    FId: TGuid;
    FActive: Boolean;
    FDomainId: TGuid;
    FPersonId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDomain: TDomainEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FPerson: TPersonEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('DomainId', [cpRequired])]
    [ForeignJoinColumn('DomainId', '[domain].[domains]', 'Id')]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('PersonId', [cpRequired])]
    [ForeignJoinColumn('PersonId', '[person].[persons]', 'Id')]
    property PersonId: TGuid read FPersonId write FPersonId;
  public
    property Domain: TDomainEntity read FDomain;
    property Person: TPersonEntity read FPerson;
  end;

implementation

end.
