unit Fiscal.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Collections,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[ncms]', '[fiscal]')]
  TNcmEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FDescription: string;
    FStartValidity: Nullable<TDateTime>;
    FEndValidity: Nullable<TDateTime>;
    FActive: Boolean;
    FExTipi: Nullable<string>;
    FPublishedAt: Nullable<TDateTime>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Description', [cpRequired])]
    property Description: string read FDescription write FDescription;
    [Column('StartValidity')]
    property StartValidity: Nullable<TDateTime> read FStartValidity write FStartValidity;
    [Column('EndValidity')]
    property EndValidity: Nullable<TDateTime> read FEndValidity write FEndValidity;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('ExTipi')]
    property ExTipi: Nullable<string> read FExTipi write FExTipi;
    [Column('PublishedAt')]
    property PublishedAt: Nullable<TDateTime> read FPublishedAt write FPublishedAt;
  end;

implementation

end.
