unit Telecom.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[areacodes]', '[telecom]')]
  TAreaCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FAreaCode: string;
    FStateId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('AreaCode', [cpRequired])]
    property AreaCode: string read FAreaCode write FAreaCode;
    [Column('StateId', [cpRequired])]
    property StateId: TGuid read FStateId write FStateId;
  end;

implementation

end.
