unit Country.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[countries]', '[country]')]
  TCountryEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FDialCode: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('DialCode', [cpRequired])]
    property DialCode: string read FDialCode write FDialCode;
  end;

  [Entity]
  [Table('[codes]', '[country]')]
  TCountryCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FCodeType: string;
    FCode: string;
    FCountryId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('CodeType', [cpRequired])]
    property CodeType: string read FCodeType write FCodeType;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('CountryId', [cpRequired])]
    property CountryId: TGuid read FCountryId write FCountryId;
  end;

  [Entity]
  [Table('[nationalities]', '[country]')]
  TNationalityEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
  end;

implementation

end.

