unit Domain.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[domains]', '[domain]')]
  TDomainEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FReserved: Boolean;
    FManagedById: Nullable<TGuid>;
    FParentId: Nullable<TGuid>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Reserved', [cpRequired])]
    property Reserved: Boolean read FReserved write FReserved;
    [Column('ManagedById')]
    property ManagedById: Nullable<TGuid> read FManagedById write FManagedById;
    [Column('ParentId')]
    property ParentId: Nullable<TGuid> read FParentId write FParentId;
  end;

  [Entity]
  [Table('[accesses]', '[domain]')]
  TAccessEntity = class(TEntity)
  private
    FId: TGuid;
    FReserved: Boolean;
    FDomainId: TGuid;
    FUserId: TGuid;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Reserved', [cpRequired])]
    property Reserved: Boolean read FReserved write FReserved;
    [Column('DomainId', [cpRequired])]
    property DomainId: TGuid read FDomainId write FDomainId;
    [Column('UserId', [cpRequired])]
    property UserId: TGuid read FUserId write FUserId;
  end;

implementation

end.
