unit Catalog.Inf.Entities;

interface

uses
{PROJECT}
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  TCatalogItemType = (
    Product,
    Service
  );

  [Entity]
  [Table('[items]', '[catalog]')]
  TCatalogItem = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FDescription: string;
    FActive: Boolean;
    FCostPrice: Currency;
    FSalePrice: Currency;
    FItemType: TCatalogItemType;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Description', [cpRequired])]
    property Description: string read FDescription write FDescription;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('CostPrice', [cpRequired])]
    property CostPrice: Currency read FCostPrice write FCostPrice;
    [Column('SalePrice', [cpRequired])]
    property SalePrice: Currency read FSalePrice write FSalePrice;
    [Column('ItemType', [cpRequired, cpHidden])]
    property ItemType: TCatalogItemType read FItemType write FItemType;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt;
    [Column('UpdatedAt')]
    property UpdatedAt;
  end;

implementation

end.
