unit Catalog.Inf.Entities;

interface

uses
{PROJECT}
  Domain.Inf.Entities,
  General.Dom.Common.SystemCatalog,
  General.Inf.Entities,
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Collections,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[unit_measures]', '[catalog]')]
  TUnitMeasureEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FSymbol: string;
    FMeasureTypeId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FMeasureType: TCategoryEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Symbol', [cpRequired])]
    property Symbol: string read FSymbol write FSymbol;
    [Column('MeasureTypeId', [cpRequired])]
    [ForeignJoinColumn('MeasureTypeId', '[general].[categories]', 'Id')]
    property MeasureTypeId: TGuid read FMeasureTypeId write FMeasureTypeId;
  public
    property MeasureType: TCategoryEntity read FMeasureType;
  end;

  [Entity]
  [Table('[items]', '[catalog]')]
  [Inheritence(isJoined)]
  TItemEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FDescription: string;
    FActive: Boolean;
    FCostPrice: Currency;
    FSalePrice: Currency;
    FItemTypeId: TGuid;
    FUnitMeasureId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FItemType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
  protected
    procedure SetItemTypeId(const AValue: TGuid);
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Description', [cpRequired])]
    property Description: string read FDescription write FDescription;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('CostPrice', [cpRequired])]
    property CostPrice: Currency read FCostPrice write FCostPrice;
    [Column('SalePrice', [cpRequired])]
    property SalePrice: Currency read FSalePrice write FSalePrice;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt;
    [Column('UpdatedAt')]
    property UpdatedAt;
    [Column('ItemTypeId', [cpRequired])]
    [ForeignJoinColumn('ItemTypeId', '[general].[categories]', 'Id')]
    property ItemTypeId: TGuid read FItemTypeId;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
  public
    property ItemType: TCategoryEntity read FItemType;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
  end;

  TConversionEntity = class;
  TGridEntity = class;

  [Entity]
  [Table('[products]', '[catalog]')]
  TProductEntity = class(TItemEntity)
  private
    FNcmId: TGuid;
    function GetConversions: IList<TConversionEntity>;
  private
    [OneToMany(False, [ckCascadeAll])]
    FConversions: Lazy<IList<TConversionEntity>>;
  public
    [Column('NcmId', [cpRequired])]
    property NcmId: TGuid read FNcmId write FNcmId;
  public
    property Conversions: IList<TConversionEntity> read GetConversions;
  public
    constructor Create;
  end;

  [Entity]
  [Table('[conversions]', '[catalog]')]
  TConversionEntity = class(TEntity)
  private
    FId: TGuid;
    FUnitMeasureId: TGuid;
    FConversionFactor: Currency;
    FIsPurchaseDefault: Boolean;
    FIsSalesDefault: Boolean;
    FProductId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FProduct: TProductEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
    [Column('ConversionFactor', [cpRequired])]
    property ConversionFactor: Currency read FConversionFactor write FConversionFactor;
    [Column('IsPurchaseDefault', [cpRequired])]
    property IsPurchaseDefault: Boolean read FIsPurchaseDefault write FIsPurchaseDefault;
    [Column('IsSalesDefault', [cpRequired])]
    property IsSalesDefault: Boolean read FIsSalesDefault write FIsSalesDefault;
    [Column('ProductId', [cpRequired])]
    [ForeignJoinColumn('ProductId', '[catalog].[products]', 'Id')]
    property ProductId: TGuid read FProductId write FProductId;
  public
    property Product: TProductEntity read FProduct;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
  end;

  TColumnEntity = class;
  TVariantEntity = class;

  [Entity]
  [Table('[grids]', '[catalog]')]
  TGridEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
    FStockControlled: Boolean;
    FProductId: TGuid;
    function GetColumns: IList<TColumnEntity>;
    function GetVariants: IList<TVariantEntity>;
  private
    [OneToMany(False, [ckCascadeAll])]
    FColumns: Lazy<IList<TColumnEntity>>;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FProduct: TProductEntity;
    [OneToMany(False, [ckCascadeAll])]
    FVariants: Lazy<IList<TVariantEntity>>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('StockControlled', [cpRequired])]
    property StockControlled: Boolean read FStockControlled write FStockControlled;
    [Column('ProductId', [cpRequired])]
    [ForeignJoinColumn('ProductId', '[catalog].[products]', 'Id')]
    property ProductId: TGuid read FProductId write FProductId;
  public
    property Columns: IList<TColumnEntity> read GetColumns;
    property Product: TProductEntity read FProduct;
    property Variants: IList<TVariantEntity> read GetVariants;
  end;

  TAttributeEntity = class;

  [Entity]
  [Table('[columns]', '[catalog]')]
  TColumnEntity = class(TEntity)
  private
    FId: TGuid;
    FOrder: Integer;
    FAttributeId: TGuid;
    FDataTypeId: TGuid;
    FGridId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FAttribute: TAttributeEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDataType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FGrid: TGridEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Order', [cpRequired])]
    property Order: Integer read FOrder write FOrder;
    [Column('AttributeId', [cpRequired])]
    [ForeignJoinColumn('AttributeId', '[catalog].[attributes]', 'Id')]
    property AttributeId: TGuid read FAttributeId write FAttributeId;
    [Column('DataTypeId', [cpRequired])]
    [ForeignJoinColumn('DataTypeId', '[general].[categories]', 'Id')]
    property DataTypeId: TGuid read FDataTypeId write FDataTypeId;
    [Column('GridId', [cpRequired])]
    [ForeignJoinColumn('GridId', '[catalog].[grids]', 'Id')]
    property GridId: TGuid read FGridId write FGridId;
  public
    property Attribute: TAttributeEntity read FAttribute;
    property DataType: TCategoryEntity read FDataType;
    property Grid: TGridEntity read FGrid;
  end;

  [Entity]
  [Table('[attributes]', '[catalog]')]
  TAttributeEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
  end;

  [Entity]
  [Table('[attribute_codes]', '[catalog]')]
  TAttributeCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FCodeType: string;
    FAttributeId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FAttribute: TAttributeEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('CodeType', [cpRequired])]
    property CodeType: string read FCodeType write FCodeType;
    [Column('AttributeId', [cpRequired])]
    [ForeignJoinColumn('AttributeId', '[catalog].[attributes]', 'Id')]
    property AttributeId: TGuid read FAttributeId write FAttributeId;
  public
    property Attribute: TAttributeEntity read FAttribute;
  end;

  TVariantValueEntity = class;

  [Entity]
  [Table('[variants]', '[catalog]')]
  TVariantEntity = class(TEntity)
  private
    FId: TGuid;
    FSKU: string;
    FGtin: Nullable<string>;
    FActive: Boolean;
    FGridId: TGuid;
    function GetValues: IList<TVariantValueEntity>;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FGrid: TGridEntity;
    [OneToMany(False, [ckCascadeAll])]
    FValues: Lazy<IList<TVariantValueEntity>>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('SKU', [cpRequired])]
    property SKU: string read FSKU write FSKU;
    [Column('Gtin')]
    property Gtin: Nullable<string> read FGtin write FGtin;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('GridId', [cpRequired])]
    [ForeignJoinColumn('GridId', '[catalog].[grids]', 'Id')]
    property GridId: TGuid read FGridId write FGridId;
  public
    property Grid: TGridEntity read FGrid;
    property Values: IList<TVariantValueEntity> read GetValues;
  end;

  [Entity]
  [Table('[variant_values]', '[catalog]')]
  TVariantValueEntity = class(TEntity)
  private
    FId: TGuid;
    FVariantId: TGuid;
    FColumnId: TGuid;
    FValue: string;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FColumn: TColumnEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('ColumnId', [cpRequired])]
    [ForeignJoinColumn('ColumnId', '[catalog].[columns]', 'Id')]
    property ColumnId: TGuid read FColumnId write FColumnId;
    [Column('Value', [cpRequired])]
    property Value: string read FValue write FValue;
  public
    property Column: TColumnEntity read FColumn;
    property Variant: TVariantEntity read FVariant;
  end;

  [Entity]
  [Table('[services]', '[catalog]')]
  TServiceEntity = class(TItemEntity)
  public
    constructor Create;
  end;

implementation

{ TItemEntity }

procedure TItemEntity.SetItemTypeId(const AValue: TGuid);
begin
  FItemTypeId := AValue;
end;

{ TProductEntity }

constructor TProductEntity.Create;
begin
  inherited Create;
  SetItemTypeId(TSystemCatalog.ProductTypeId);
end;

function TProductEntity.GetConversions: IList<TConversionEntity>;
begin
  Result := FConversions;
end;

{ TProductGridEntity }

function TGridEntity.GetColumns: IList<TColumnEntity>;
begin
  Result := FColumns;
end;

function TGridEntity.GetVariants: IList<TVariantEntity>;
begin
  Result := FVariants;
end;

{ TProductVariantEntity }

function TVariantEntity.GetValues: IList<TVariantValueEntity>;
begin
  Result := FValues;
end;

{ TServiceEntity }

constructor TServiceEntity.Create;
begin
  inherited Create;
  SetItemTypeId(TSystemCatalog.ServiceTypeId);
end;

end.
