unit Catalog.Inf.Entities;

interface

uses
{PROJECT}
  CRM.Inf.Entities,
  Domain.Inf.Entities,
  Fiscal.Inf.Entities,
  General.Dom.Common.SystemCatalog,
  General.Inf.Entities,
  Shared.Inf.Entities.Entity,
{SPRING}
  Spring,
  Spring.Collections,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('[configs]', '[catalog]')]
  TConfigEntity = class(TEntity)
  private
    FId: Integer;
    FProductCodePattern: Nullable<string>;
    FServiceCodePattern: Nullable<string>;
  public
    [Column('Id', [cpPrimaryKey])]
    property Id: Integer read FId write FId;
    [Column('ProductCodePattern', [cpDontInsert])]
    property ProductCodePattern: Nullable<string> read FProductCodePattern write FProductCodePattern;
    [Column('ServiceCodePattern', [cpDontInsert])]
    property ServiceCodePattern: Nullable<string> read FServiceCodePattern write FServiceCodePattern;
  end;

  [Entity]
  [Table('[unit_measures]', '[catalog]')]
  TUnitMeasureEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FSymbol: string;
    FMeasureTypeId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FMeasureType: TCategoryEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Symbol', [cpRequired])]
    property Symbol: string read FSymbol write FSymbol;
    [Column('MeasureTypeId', [cpRequired])]
    [ForeignJoinColumn('MeasureTypeId', '[general].[categories]', 'Id')]
    property MeasureTypeId: TGuid read FMeasureTypeId write FMeasureTypeId;
  public
    property MeasureType: TCategoryEntity read FMeasureType;
  end;

  [Entity]
  [Table('[items]', '[catalog]')]
  [Inheritence(isJoined)]
  TItemEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FName: string;
    FDescription: string;
    FActive: Boolean;
    FCostPrice: Currency;
    FSalePrice: Currency;
    FItemTypeId: TGuid;
    FUnitMeasureId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FItemType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
  protected
    procedure SetItemTypeId(const AValue: TGuid);
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [AutoGenerated]
    [Column('Code')]
    property Code: string read FCode write FCode;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
    [Column('Description', [cpRequired])]
    property Description: string read FDescription write FDescription;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('CostPrice', [cpRequired])]
    property CostPrice: Currency read FCostPrice write FCostPrice;
    [Column('SalePrice', [cpRequired])]
    property SalePrice: Currency read FSalePrice write FSalePrice;
    [Column('CreatedAt', [cpRequired])]
    property CreatedAt;
    [Column('UpdatedAt')]
    property UpdatedAt;
    [Column('ItemTypeId', [cpRequired])]
    [ForeignJoinColumn('ItemTypeId', '[general].[categories]', 'Id')]
    property ItemTypeId: TGuid read FItemTypeId;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
  public
    property ItemType: TCategoryEntity read FItemType;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
  end;

  TColumnEntity = class;
  TConversionEntity = class;
  TVariantEntity = class;

  [Entity]
  [Table('[products]', '[catalog]')]
  TProductEntity = class(TItemEntity)
  private
    FNcmId: TGuid;
    FExpirationControlled: Boolean;
    FLotControlled: Boolean;
    FStockControlled: Boolean;
    FManufacturerId: Nullable<TGuid>;
    function GetColumns: IList<TColumnEntity>;
    function GetConversions: IList<TConversionEntity>;
    function GetVariants: IList<TVariantEntity>;
  private
    [OneToMany(False, [ckCascadeAll])]
    FColumns: Lazy<IList<TColumnEntity>>;
    [OneToMany(False, [ckCascadeAll])]
    FConversions: Lazy<IList<TConversionEntity>>;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FManufacturer: TManufacturerEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FNCM: TNcmEntity;
    [OneToMany(False, [ckCascadeAll])]
    FVariants: Lazy<IList<TVariantEntity>>;
  public
    [Column('NcmId', [cpRequired])]
    [ForeignJoinColumn('NcmId', '[fiscal].[ncms]', 'Id')]
    property NcmId: TGuid read FNcmId write FNcmId;
    [Column('LotControlled', [cpRequired])]
    property LotControlled: Boolean read FLotControlled write FLotControlled;
    [Column('ExpirationControlled', [cpRequired])]
    property ExpirationControlled: Boolean read FExpirationControlled write FExpirationControlled;
    [Column('StockControlled', [cpRequired])]
    property StockControlled: Boolean read FStockControlled write FStockControlled;
    [Column('ManufacturerId')]
    [ForeignJoinColumn('ManufacturerId', '[crm].[manufacturers]', 'Id')]
    property ManufacturerId: Nullable<TGuid> read FManufacturerId write FManufacturerId;
  public
    property Columns: IList<TColumnEntity> read GetColumns;
    property Conversions: IList<TConversionEntity> read GetConversions;
    property Manufacturer: TManufacturerEntity read FManufacturer;
    property NCM: TNcmEntity read FNCM;
    property Variants: IList<TVariantEntity> read GetVariants;
  public
    constructor Create;
  end;

  [Entity]
  [Table('[conversions]', '[catalog]')]
  TConversionEntity = class(TEntity)
  private
    FId: TGuid;
    FUnitMeasureId: TGuid;
    FConversionFactor: Currency;
    FIsPurchaseDefault: Boolean;
    FIsSalesDefault: Boolean;
    FProductId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FProduct: TProductEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FUnitMeasure: TUnitMeasureEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('UnitMeasureId', [cpRequired])]
    [ForeignJoinColumn('UnitMeasureId', '[catalog].[unit_measures]', 'Id')]
    property UnitMeasureId: TGuid read FUnitMeasureId write FUnitMeasureId;
    [Column('ConversionFactor', [cpRequired])]
    property ConversionFactor: Currency read FConversionFactor write FConversionFactor;
    [Column('IsPurchaseDefault', [cpRequired])]
    property IsPurchaseDefault: Boolean read FIsPurchaseDefault write FIsPurchaseDefault;
    [Column('IsSalesDefault', [cpRequired])]
    property IsSalesDefault: Boolean read FIsSalesDefault write FIsSalesDefault;
    [Column('ProductId', [cpRequired])]
    [ForeignJoinColumn('ProductId', '[catalog].[products]', 'Id')]
    property ProductId: TGuid read FProductId write FProductId;
  public
    property Product: TProductEntity read FProduct;
    property UnitMeasure: TUnitMeasureEntity read FUnitMeasure;
  end;

  TAttributeEntity = class;

  [Entity]
  [Table('[columns]', '[catalog]')]
  TColumnEntity = class(TEntity)
  private
    FId: TGuid;
    FOrder: Integer;
    FAttributeId: TGuid;
    FDataTypeId: TGuid;
    FProductId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FAttribute: TAttributeEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FDataType: TCategoryEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FProduct: TProductEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Order', [cpRequired])]
    property Order: Integer read FOrder write FOrder;
    [Column('AttributeId', [cpRequired])]
    [ForeignJoinColumn('AttributeId', '[catalog].[attributes]', 'Id')]
    property AttributeId: TGuid read FAttributeId write FAttributeId;
    [Column('DataTypeId', [cpRequired])]
    [ForeignJoinColumn('DataTypeId', '[general].[categories]', 'Id')]
    property DataTypeId: TGuid read FDataTypeId write FDataTypeId;
    [Column('ProductId', [cpRequired])]
    [ForeignJoinColumn('ProductId', '[catalog].[products]', 'Id')]
    property ProductId: TGuid read FProductId write FProductId;
  public
    property Attribute: TAttributeEntity read FAttribute;
    property DataType: TCategoryEntity read FDataType;
    property Product: TProductEntity read FProduct;
  end;

  [Entity]
  [Table('[attributes]', '[catalog]')]
  TAttributeEntity = class(TEntity)
  private
    FId: TGuid;
    FName: string;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Name', [cpRequired])]
    property Name: string read FName write FName;
  end;

  [Entity]
  [Table('[attribute_codes]', '[catalog]')]
  TAttributeCodeEntity = class(TEntity)
  private
    FId: TGuid;
    FCode: string;
    FCodeType: string;
    FAttributeId: TGuid;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FAttribute: TAttributeEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('Code', [cpRequired])]
    property Code: string read FCode write FCode;
    [Column('CodeType', [cpRequired])]
    property CodeType: string read FCodeType write FCodeType;
    [Column('AttributeId', [cpRequired])]
    [ForeignJoinColumn('AttributeId', '[catalog].[attributes]', 'Id')]
    property AttributeId: TGuid read FAttributeId write FAttributeId;
  public
    property Attribute: TAttributeEntity read FAttribute;
  end;

  TGridEntity = class;

  [Entity]
  [Table('[variants]', '[catalog]')]
  TVariantEntity = class(TEntity)
  private
    FId: TGuid;
    FSKU: string;
    FGtin: Nullable<string>;
    FActive: Boolean;
    FProductId: TGuid;
    function GetGridValues: IList<TGridEntity>;
  private
    [OneToMany(False, [ckCascadeAll])]
    FGridValues: Lazy<IList<TGridEntity>>;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('SKU', [cpRequired])]
    property SKU: string read FSKU write FSKU;
    [Column('Gtin')]
    property Gtin: Nullable<string> read FGtin write FGtin;
    [Column('Active', [cpRequired])]
    property Active: Boolean read FActive write FActive;
    [Column('ProductId', [cpRequired])]
    [ForeignJoinColumn('ProductId', '[catalog].[products]', 'Id')]
    property ProductId: TGuid read FProductId write FProductId;
  public
    property GridValues: IList<TGridEntity> read GetGridValues;
  end;

  [Entity]
  [Table('[grids]', '[catalog]')]
  TGridEntity = class(TEntity)
  private
    FId: TGuid;
    FVariantId: TGuid;
    FColumnId: TGuid;
    FValue: string;
  private
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FColumn: TColumnEntity;
    [ManyToOne(False, [ckCascadeAll], 'Id')]
    FVariant: TVariantEntity;
  public
    [AutoGenerated]
    [Column('Id', [cpPrimaryKey])]
    property Id: TGuid read FId write FId;
    [Column('VariantId', [cpRequired])]
    [ForeignJoinColumn('VariantId', '[catalog].[variants]', 'Id')]
    property VariantId: TGuid read FVariantId write FVariantId;
    [Column('ColumnId', [cpRequired])]
    [ForeignJoinColumn('ColumnId', '[catalog].[columns]', 'Id')]
    property ColumnId: TGuid read FColumnId write FColumnId;
    [Column('Value', [cpRequired])]
    property Value: string read FValue write FValue;
  public
    property Column: TColumnEntity read FColumn;
    property Variant: TVariantEntity read FVariant;
  end;

  [Entity]
  [Table('[services]', '[catalog]')]
  TServiceEntity = class(TItemEntity)
  public
    constructor Create;
  end;

implementation

{ TItemEntity }

procedure TItemEntity.SetItemTypeId(const AValue: TGuid);
begin
  FItemTypeId := AValue;
end;

{ TProductEntity }

constructor TProductEntity.Create;
begin
  inherited Create;
  SetItemTypeId(TSystemCatalog.ProductTypeId);
end;

function TProductEntity.GetColumns: IList<TColumnEntity>;
begin
  Result := FColumns;
end;

function TProductEntity.GetConversions: IList<TConversionEntity>;
begin
  Result := FConversions;
end;

function TProductEntity.GetVariants: IList<TVariantEntity>;
begin
  Result := FVariants;
end;

{ TVariantEntity }

function TVariantEntity.GetGridValues: IList<TGridEntity>;
begin
  Result := FGridValues;
end;

{ TServiceEntity }

constructor TServiceEntity.Create;
begin
  inherited Create;
  SetItemTypeId(TSystemCatalog.ServiceTypeId);
end;

end.
